version: '2'

services:
  main:
    build: .
    restart: unless-stopped
    privileged: false
    cap_add:
      - NET_ADMIN
    ports:
      - "22233:22"
    environment:
      - EDITOR=vim
    volumes:
      - ../:/home/leetcode
    networks:
        default:

networks:
    default:
